Repository kookmin-sw/capstone-2023-15, pull requests merged in 2023-05, with the labels that each got.

#71 ???: 이거 바꿔주세요
  front/public/favicon.ico
  front/public/index.html
  front/public/logo.png
  front/public/logo192.png
  front/public/logo512.png
  front/public/mainicon.ico
  front/public/manifest.json
Labels: Web

#65 - result page & header cursor
  front/Dockerfile
  front/conf/conf.d/default.conf
  front/src/App.js
  front/src/components/Header.js
  front/src/pages/ResultCheckPage.js
  front/src/pages/ResultPageList.js
Labels: Feature, Web

#75 ai/feature/ai_model: ThreeF model upload
  model/README.md
  model/caps_runner.py
  model/common/__init__.py
  model/common/__pycache__/__init__.cpython-310.pyc
  model/common/__pycache__/common.cpython-310.pyc
  model/common/__pycache__/eval.cpython-310.pyc
  model/common/__pycache__/train.cpython-310.pyc
  model/common/common.py
  model/common/eval.py
  model/common/train.py
  model/datasets/__init__.py
  model/datasets/datasets.py
  model/datasets/imagenet_fix_preprocess.py
  model/datasets/lsun_fix_preprocess.py
  model/eval.py
  model/evals/__init__.py
  model/evals/evals.py
  model/evals/ood_pre.py
  model/models/__init__.py
  model/models/base_model.py
  model/models/classifier.py
  model/models/resnet.py
  model/models/resnet_imagenet.py
  model/models/transform_layers.py
  model/ours_runner.ipynb
  model/train.py
  model/training/__init__.py
  model/training/contrastive_loss.py
  model/training/scheduler.py
  model/training/sup/__init__.py
  model/training/sup/sup_CSI_linear.py
  model/training/sup/sup_linear.py
  model/training/sup/sup_simclr.py
  model/training/sup/sup_simclr_CSI.py
  model/training/unsup/.ipynb_checkpoints/simclr_CSI-checkpoint.py
  model/training/unsup/__init__.py
  model/training/unsup/__pycache__/__init__.cpython-310.pyc
  model/training/unsup/__pycache__/simclr_CSI.cpython-310.pyc
  model/training/unsup/simclr.py
  model/training/unsup/simclr_CSI.py
  model/utils/__init__.py
  model/utils/temperature_scaling.py
  model/utils/utils.py
Labels: AI

#77 feature : 구글폼 연결
  front/src/pages/MainPage.js
Labels: Feature, Web

#81 IntroPage 구현
  front/src/App.js
  front/src/components/Header.js
  front/src/components/IntroComponent/ProcessComponent.js
  front/src/components/IntroComponent/TitleComponent.js
  front/src/components/IntroComponent/ValueComponent.js
  front/src/pages/IntroPage.js
  front/src/statics/images/bg-char.png
  front/src/statics/images/bg-color.png
  front/src/statics/images/bg-purple.png
  front/src/statics/images/gen-img.png
Labels: Feature, Web

#87 Front 이슈 해결 & 코드 리팩토링 & uiux 개선
  front/package.json
  front/src/App.js
  front/src/components/CasesComponents/CaseComponent.js
  front/src/components/Footer.js
  front/src/components/Header.js
  front/src/components/IntroComponent/ProcessComponent.js
  front/src/components/IntroComponent/TitleComponent.js
  front/src/components/IntroComponent/TitleWriterComponent.js
  front/src/components/IntroComponent/ValueComponent.js
  front/src/components/MainComponents/MainCaseComponent.js
  front/src/components/Modal.js
  front/src/components/ResultComponents/MaliciousBtnComponent.js
  front/src/pages/IntroPage.js
  front/src/pages/MainPage.js
  front/src/pages/ResultCheckPage.js
  front/src/pages/TermsPage.js
  front/yarn.lock
Labels: Feature, Web, Refactor

#97 ai/feature/ai_model : Model Deployment Guide
  model/README.md
Labels: AI
